### ISSUE TITLE
Build?

### ISSUE THREAD

**Issue by jmatsushita** [BigBlueHat/levelgraph-playground#2]
Hi there,

Been wanting to kick the tires and wondering how you generate your `dist` folder ?

Cheers,

Jun

**Comment by BigBlueHat** [comment]
Oh! Very sorry about that. I'll add it to the readme and/or an npm run script. It's just:
```
browserify index.js -o dist/index.js
```

Thanks for all you're doing @jmatsushita!

**Comment by BigBlueHat** [comment]
README updated!
https://github.com/BigBlueHat/levelgraph-playground/commit/5b4cce0431b228fc39b928e30b41715ab913c010
